Repository alkaline-ml/pmdarima, pull requests merged in 2018-12, with the labels that each got.

#71 [MRG] Greater stationarity test precision
  pmdarima/arima/stationarity.py
  pmdarima/arima/tests/test_approx.py
  pmdarima/arima/tests/test_stationarity.py
  pmdarima/arima/utils.py
Labels: bug-fix, enhancement

#75 [MRG] Support Python 3.7
  .circleci/config.yml
  .travis.yml
  Makefile
  appveyor.yml
  build_tools/appveyor/requirements.txt
  build_tools/circle/build_push_doc.sh
  build_tools/travis/install.sh
  pmdarima/_build_utils/__init__.py
  pmdarima/arima/seasonality.py
  pmdarima/arima/tests/test_seasonality.py
  pmdarima/arima/tests/test_stationarity.py
  pmdarima/compat/python.py
  requirements.txt
Labels: python 3.7

#60 [MRG + 1] Generate plot diff rmse
  appveyor.yml
  pmdarima/arima/tests/input_images/plot_diagnostics_arima.png
  pmdarima/arima/tests/input_images/plot_diagnostics_arma.png
  pmdarima/arima/tests/input_images/plot_diagnostics_sarimax.png
  pmdarima/arima/tests/test_arima.py
  pmdarima/arima/tests/test_arima_diagnostics.py
Labels: cicd

#77 [MRG+1] Py37 build artifacts
  .travis.yml
  build_tools/travis/after_wheel_build.sh
  build_tools/travis/build_manywheels_linux.sh
Labels: cicd, python 3.7, v1.1.0

#81 [MRG] Improve codecov tolerance
  .codecov.yml
  doc/tips_and_tricks.rst
Labels: cicd

#83 [MRG] Clean travisci techdebt
  .gitignore
  .travis.yml
  build_tools/travis/after_wheel_build.sh
  build_tools/travis/build_wheels.sh
  build_tools/travis/install.sh
  build_tools/travis/test_script.sh
  doc/contributing.rst
  pmdarima/__init__.py
  pmdarima/arima/tests/test_approx.py
  pmdarima/arima/tests/test_arima.py
  pmdarima/utils/__init__.py
  pmdarima/utils/testing.py
  pmdarima/utils/tests/test_testing.py
  setup.cfg
  setup32.cfg
Labels: cicd, tech-debt
