Repository alkaline-ml/pmdarima, pull requests merged in 2019-04, with the labels that each got.

#118 [MRG+1] Fourier transformation
  pmdarima/preprocessing/endog/__init__.py
  pmdarima/preprocessing/endog/fourier.py
  pmdarima/preprocessing/endog/tests/test_boxcox.py
  pmdarima/preprocessing/endog/tests/test_fourier.py
Labels: v1.2.0

#129 [MRG+1] Add Azure pipelines CI/CD
  Makefile
  README.md
  azure-pipelines.yml
  build_tools/azure/requirements.txt
  pmdarima/__init__.py
Labels: cicd

#131 [MRG+1] Fix deploy logic on Azure Pipelines
  azure-pipelines.yml
Labels: :beetle: :hammer: : bug-fix, cicd

#132 [MRG+1] Remove appveyor
  README.md
  appveyor.yml
  build_tools/appveyor/install.ps1
  build_tools/appveyor/requirements.txt
  build_tools/appveyor/run_with_env.cmd
Labels: cicd

#134 [MRG+1] Fixed Travis build
  build_tools/travis/after_wheel_build.sh
Labels: :beetle: : bug, cicd

#135 [MRG+1] Mac builds on azure
  azure-pipelines.yml
  build_tools/azure/build_and_deploy.yml
  build_tools/azure/jobs.yml
  build_tools/travis/after_wheel_build.sh
  doc/index.rst
  doc/whats_new.rst
  pmdarima/__init__.py
  setup.py
Labels: cicd
