Repository alkaline-ml/pmdarima, pull requests merged in 2019-11, with the labels that each got.

#210 [MRG+2] Fixed issue #204 [DOC] Misleading doc in SlidingWindowForecastCV
  pmdarima/model_selection/_split.py
Labels: doc

#214 [MRG+1] Use tags for __version__
  .circleci/config.yml
  .gitignore
  MANIFEST.in
  Makefile
  build_tools/azure/build_and_deploy.yml
  build_tools/azure/jobs.yml
  build_tools/azure/test_version_tagging.sh
  build_tools/circle/build_push_doc.sh
  build_tools/circle/build_wheel.sh
  build_tools/circle/test_version_tagging.sh
  build_tools/doc/doc_requirements.txt
  build_tools/get_tag.py
  doc/modules/classes.rst
  pmdarima/__init__.py
  requirements.txt
Labels: cicd, maintenance

#236 [MRG+2] R diffinv parity
  .gitignore
  MANIFEST.in
  doc/whats_new.rst
  pmdarima/setup.py
  pmdarima/utils/_array.pyx
  pmdarima/utils/array.py
  pmdarima/utils/setup.py
  pmdarima/utils/tests/test_array.py
Labels: feature request

#237 [MRG+2] Absolute coverage
  .codecov.yml
Labels: cicd

#239 [MRG + 1] Fix doc typo
  doc/whats_new.rst
Labels: doc
