Repository alkaline-ml/pmdarima, pull requests merged in 2019-12, with the labels that each got.

#251 [MRG+1] sdist install check on Windows and Mac
  build_tools/azure/build_and_deploy.yml
  build_tools/azure/jobs.yml
Labels: cicd

#259 [MRG+1] Decompose Shape Fix
  examples/seasonal_trend_decomposition_additive.ipynb
  examples/seasonal_trend_decomposition_multiplicative.ipynb
  pmdarima/arima/seasonality.py
  pmdarima/arima/tests/test_seasonality.py
Labels: :beetle: :hammer: : bug-fix

#269 [MRG+2] Host Pypy dependencies ourselves
  .github/workflows/build_pypy_dependencies.yml
Labels: cicd

#278 [MRG+1] Use new pypy image
  .circleci/config.yml
Labels: cicd

#263 [MRG+2] First-party Conda Distributions
  .github/workflows/build_and_deploy.yml
  .github/workflows/test_tagging.yml
  .gitignore
  Makefile
  README.md
  azure-pipelines.yml
  build_tools/azure/build_and_deploy.yml
  build_tools/azure/conda/deploy.yml
  build_tools/azure/conda/linux.yml
  build_tools/azure/conda/mac.yml
  build_tools/azure/conda/windows.yml
  build_tools/azure/jobs.yml
  build_tools/azure/meta_template.yml.j2
  build_tools/azure/render_meta.py
  build_tools/build_requirements.txt
  build_tools/get_tag.py
  build_tools/github/test_version_tagging.sh
  doc/whats_new.rst
Labels: cicd

#248 [MRG+2] Python 3.8 support
  .circleci/config.yml
  .github/workflows/build_and_deploy.yml
  README.md
  build_tools/azure/conda/linux.yml
  build_tools/azure/conda/mac.yml
  build_tools/azure/conda/windows.yml
  build_tools/build_requirements.txt
  doc/whats_new.rst
  requirements.txt
Labels: python 3.8

#282 [MRG+1] Don't rebuild pypy deps on master
  .github/workflows/build_pypy_dependencies.yml
Labels: :beetle: :hammer: : bug-fix, cicd

#284 [MRG+1] Fix README
  README.md
Labels: doc
