Repository alkaline-ml/pmdarima, pull requests merged in 2020-04, with the labels that each got.

#317 [MRG+2] Fix for issue#316 decompose error where m is odd
  .gitignore
  pmdarima/arima/seasonality.py
  pmdarima/arima/tests/test_seasonality.py
Labels: :beetle: :hammer: : bug-fix

#320 [MRG+1] Fix deploy
  build_tools/azure/conda/common.yml
  build_tools/azure/conda/deploy.sh
  build_tools/circle/build_wheel.sh
Labels: :beetle: :hammer: : bug-fix, cicd

#323 [MRG+1] ValueError for predict_in_sample when start < d
  doc/whats_new.rst
  pmdarima/arima/arima.py
  pmdarima/arima/tests/test_arima.py
Labels: :beetle: :hammer: : bug-fix

#325 [MRG+2] Remove conda support
  .gitignore
  MANIFEST.in
  README.md
  azure-pipelines.yml
  build_tools/azure/conda/common.yml
  build_tools/azure/conda/deploy.sh
  build_tools/azure/conda/deploy.yml
  build_tools/azure/conda/unix.yml
  build_tools/azure/conda/windows.yml
  build_tools/azure/meta_template.yml.j2
  build_tools/azure/render_meta.py
  build_tools/azure/test_version_tagging.sh
  build_tools/circle/deploy.sh
  build_tools/get_tag.py
  build_tools/github/deploy.sh
  doc/whats_new.rst
Labels: cicd

#324 MAINT: Rewrite check_is_fitted
  pmdarima/arima/arima.py
  pmdarima/compat/sklearn.py
  pmdarima/compat/tests/test_sklearn.py
  pmdarima/pipeline.py
  pmdarima/preprocessing/endog/boxcox.py
  pmdarima/preprocessing/exog/fourier.py
Labels: :put_litter_in_its_place: : tech-debt
