Repository alkaline-ml/pmdarima, pull requests merged in 2022-04, with the labels that each got.

#486 [MRG] Don't use deprecated circlci/classic machines
  .circleci/config.yml
Labels: cicd, maintenance

#491 [MRG+1] Fix bug introduced by latest setuptools
  setup.py
Labels: cicd, :beetle: :hammer: : bug-fix, dependency-issue

#496 [MRG+1] Add 'concurrency' block to GHA and fix build warnings
  .github/workflows/build_and_deploy.yml
  .github/workflows/nightly_cron.yml
  .github/workflows/test_tagging.yml
  pmdarima/arima/seasonality.py
  pmdarima/model_selection/_split.py
  pmdarima/utils/tests/test_array.py
Labels: cicd

#498 [MRG+1] Sunset 32-bit builds
  .github/workflows/build_and_deploy.yml
  README.md
  doc/whats_new.rst
Labels: cicd, v2.0.0

#500 [MRG+1] Allow `predict_in_sample` for non-integer start/end indices
  doc/whats_new.rst
  pmdarima/arima/approx.py
  pmdarima/arima/arima.py
  pmdarima/arima/auto.py
  pmdarima/arima/seasonality.py
  pmdarima/arima/stationarity.py
  pmdarima/arima/tests/test_arima.py
  pmdarima/metrics.py
  pmdarima/model_selection/_validation.py
  pmdarima/pipeline.py
  pmdarima/preprocessing/base.py
  pmdarima/utils/array.py
  pmdarima/utils/tests/test_array.py
  pmdarima/utils/visualization.py
Labels: feature request, v2.0.0
